import {
  Box,
  Typography
} from "@mui/material";

export default function Home() {
  return (
    <Box
      sx={ {
        alignItems: "center",
        justifyItems: "center",
        minWidth: "100%",
        minHeight: "100vh",
        padding: "0"
      } }
    >
      <Box
        sx={ {
          display: "grid",
          alignItems: "center",
          justifyItems: "center",
          bgcolor: "primary.dark",
          minWidth: "100%",
          minHeight: "90vh",
          padding: "0"
        } }
      >
        <Box
          component="main"
          sx={ {
            display: "flex",
            alignItems: "center",
            flexDirection: "column",
            width: "100%"
          } }
        >
          <Typography
            variant="h1"
            sx={ {
              color: "primary.contrastText",
              paddingY: "0.1em"
            } }
          >
            Hello,{ " " }
            <Box
              component="code"
            >
              Next.js
            </Box>
            !
          </Typography>
          <Typography
            variant="h5"
            sx={ {
              color: "primary.contrastText",
              paddingY: "0.1em",
              textAlign: "center"
            } }
          >
            <Box
              component="code"
            >
              Next.js
            </Box>
            { " " } is a React framework that enables server-side rendering and static
            site
            generation.<br/>
            This page is a static page generated by { " " }
            <Box
              component="code"
            >
              Next.js
            </Box>
            .
          </Typography>
        </Box>
      </Box>
      <Box
        component = "footer"
        sx={ {
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          bgcolor: "primary.main",
          minWidth: "100%",
          minHeight: "10vh",
          padding: "0",
        } }
      >
        <Typography
          variant="h5"
          sx={ {
            color: "primary.contrastText",
            paddingY: "0.1em",
            textAlign: "center"
          } }
        >
          Commilitia
        </Typography>
      </Box>
    </Box>
  );
}
